// Nội dung "Kỹ năng sống" cho học sinh: nấu nướng · trồng trọt · chụp ảnh · chăm sóc da.
// Thuần dữ liệu — trang app/ky-nang đọc và render. Thêm/sửa kỹ năng ở đây.
//
// ẢNH minh hoạ: lấy từ Wikimedia Commons (upload.wikimedia.org) — không quảng cáo, rất ổn
// định, ít 404. NGUỒN bài viết: Wikipedia (ad-free). Tất cả URL đã verify trả 200.
// Nếu một ảnh lỡ hỏng, SkillsView tự ẩn ảnh và hiện emoji thay thế (không vỡ layout).

export type Skill = {
  id: string
  title: string
  emoji: string
  time: string // thời gian ước lượng
  level: 'Dễ' | 'Vừa'
  intro: string // 1 câu mở đầu
  need: string[] // nguyên liệu / dụng cụ
  steps: string[] // các bước
  tip: string // mẹo nhỏ
  img: string // ảnh minh hoạ (URL ổn định)
  imgAlt: string
  source: { label: string; url: string } // nguồn tham khảo uy tín
}

export type SkillCategory = {
  key: 'nau' | 'trong' | 'chup' | 'da'
  label: string
  emoji: string
  blurb: string
  skills: Skill[]
}

const W = 'https://upload.wikimedia.org/wikipedia/commons/'

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    key: 'nau',
    label: 'Nấu nướng',
    emoji: '🍳',
    blurb: 'Vài món cơ bản để tự lo bữa ăn khi bố mẹ vắng nhà — an toàn là trên hết.',
    skills: [
      {
        id: 'com-dien',
        title: 'Nấu cơm bằng nồi cơm điện',
        emoji: '🍚',
        time: '25 phút',
        level: 'Dễ',
        intro: 'Kỹ năng nền tảng nhất: cơm dẻo, không khê, không sống.',
        need: ['Gạo', 'Nước', 'Nồi cơm điện', 'Cốc/ca đong'],
        steps: [
          'Đong gạo, vo nhẹ 2 lần cho sạch bụi cám (đừng chà mạnh).',
          'Cho nước theo tỉ lệ ~1 gạo : 1,2 nước; hoặc đặt tay lên mặt gạo, nước ngập tới đốt đầu ngón trỏ.',
          'Lau khô đáy nồi bên ngoài rồi đặt vào, đậy nắp, bấm Cook.',
          'Khi nút bật sang Warm, để ủ thêm 10 phút rồi mới xới cho tơi.',
        ],
        tip: 'Gạo mới cần ít nước hơn, gạo cũ cần nhiều nước hơn một chút.',
        img: `${W}thumb/d/d6/Rice_Cooker_1.png/500px-Rice_Cooker_1.png`,
        imgAlt: 'Nồi cơm điện',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rice_cooker' },
      },
      {
        id: 'luoc-rau',
        title: 'Luộc rau xanh mướt',
        emoji: '🥬',
        time: '10 phút',
        level: 'Dễ',
        intro: 'Rau xanh giòn, không bị vàng úa.',
        need: ['Rau (muống, cải, su su…)', 'Nước', 'Chút muối', 'Nồi'],
        steps: [
          'Nhặt và rửa rau sạch, để ráo.',
          'Đun nước thật sôi, cho một nhúm muối (giữ màu xanh).',
          'Thả rau vào, mở vung, đảo đều; luộc nhanh 2–4 phút.',
          'Vớt ra ngay khi rau vừa chín tới, có thể ngâm nước lạnh cho giòn.',
        ],
        tip: 'Nước phải sôi mạnh trước khi cho rau, và đừng đậy vung — rau sẽ xanh hơn.',
        img: `${W}thumb/9/99/Bok_Choy_%2849553125456%29.jpg/500px-Bok_Choy_%2849553125456%29.jpg`,
        imgAlt: 'Rau cải xanh',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Bok_choy' },
      },
      {
        id: 'trung-op',
        title: 'Chiên trứng ốp la',
        emoji: '🍳',
        time: '5 phút',
        level: 'Dễ',
        intro: 'Món nhanh, đủ chất cho bữa sáng.',
        need: ['Trứng gà', 'Dầu ăn', 'Chút muối', 'Chảo'],
        steps: [
          'Bắc chảo, cho ít dầu, để lửa vừa cho dầu nóng.',
          'Đập trứng vào (đập cạnh chảo cho khỏi vỡ lòng đỏ).',
          'Rắc chút muối, chiên 1–2 phút tới khi lòng trắng se lại.',
          'Lòng đỏ lỏng thì lấy ra luôn; thích chín kỹ thì lật nhẹ thêm 30 giây.',
        ],
        tip: 'Lửa to dễ cháy mép mà lòng còn sống — để lửa vừa là chuẩn.',
        img: `${W}thumb/f/f0/Fried_Egg_2.jpg/500px-Fried_Egg_2.jpg`,
        imgAlt: 'Trứng ốp la',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Fried_egg' },
      },
      {
        id: 'mi-trung',
        title: 'Mì trứng rau đủ chất',
        emoji: '🍜',
        time: '10 phút',
        level: 'Dễ',
        intro: 'Nâng cấp gói mì thành bữa cân bằng hơn.',
        need: ['1 gói mì', '1 quả trứng', 'Ít rau xanh', 'Hành lá'],
        steps: [
          'Đun sôi nước, cho rau vào trước cho chín.',
          'Cho vắt mì vào, đập thêm 1 quả trứng.',
          'Nấu ~3 phút cho mì mềm, trứng chín.',
          'Cho 1/2–2/3 gói gia vị (đừng cho hết cho đỡ mặn), rắc hành lá.',
        ],
        tip: 'Cho ít gia vị + thêm rau, trứng → đỡ mặn và no lâu hơn.',
        img: `${W}thumb/7/73/Mama_instant_noodle_block.jpg/500px-Mama_instant_noodle_block.jpg`,
        imgAlt: 'Vắt mì gói',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Instant_noodles' },
      },
      {
        id: 'nuoc-cham',
        title: 'Pha nước chấm chua ngọt',
        emoji: '🥢',
        time: '5 phút',
        level: 'Dễ',
        intro: 'Công thức dễ nhớ, chấm gì cũng hợp.',
        need: ['Nước mắm', 'Đường', 'Nước lọc', 'Chanh', 'Tỏi, ớt'],
        steps: [
          'Nhớ tỉ lệ 1 mắm : 1 đường : 1 chanh : 4–5 nước ấm.',
          'Khuấy cho đường tan hết.',
          'Cho tỏi ớt băm vào sau cùng để chúng nổi lên đẹp mắt.',
          'Nếm lại, thiếu vị nào thêm vị đó từng chút một.',
        ],
        tip: 'Dùng nước ấm để đường tan nhanh; cho tỏi ớt cuối cùng để nổi trên mặt.',
        img: `${W}thumb/e/ed/B%C3%BAn_tr%E1%BB%99n%2C_James_Bun%2C_Paris_27_August_2016_004.jpg/500px-B%C3%BAn_tr%E1%BB%99n%2C_James_Bun%2C_Paris_27_August_2016_004.jpg`,
        imgAlt: 'Món ăn Việt với nước chấm',
        source: { label: 'Wikipedia', url: 'https://vi.wikipedia.org/wiki/Nước_chấm' },
      },
      {
        id: 'an-toan-bep',
        title: 'An toàn khi vào bếp',
        emoji: '🧯',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Quan trọng nhất — nhớ kỹ trước khi nấu.',
        need: ['Sự cẩn thận 🙂'],
        steps: [
          'Khoá van bếp gas/tắt bếp ngay khi nấu xong.',
          'Dầu đang sôi mà bắt lửa: đậy vung/nắp kim loại cho tắt, TUYỆT ĐỐI không hắt nước.',
          'Tay ướt không chạm ổ điện, phích cắm.',
          'Cán dao quay vào trong, dao sắc cắt an toàn hơn dao cùn.',
          'Có gì không chắc → gọi người lớn, đừng ngại.',
        ],
        tip: 'Cháy dầu mỡ thì phủ kín cho tắt, không dùng nước — nước làm lửa bùng to hơn.',
        img: `${W}9/99/Gas_stove.jpg`,
        imgAlt: 'Bếp gas',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Gas_stove' },
      },
    ],
  },
  {
    key: 'trong',
    label: 'Trồng trọt',
    emoji: '🌱',
    blurb: 'Trồng vài thứ xanh ngay tại ban công hay bệ cửa sổ — vừa vui vừa có rau ăn.',
    skills: [
      {
        id: 'rau-mam',
        title: 'Trồng rau mầm trong khay',
        emoji: '🌿',
        time: '5–7 ngày',
        level: 'Dễ',
        intro: 'Nhanh thu hoạch nhất, hợp người mới bắt đầu.',
        need: ['Hạt rau mầm (cải, củ cải…)', 'Khay nông', 'Khăn giấy/bông', 'Bình xịt nước'],
        steps: [
          'Ngâm hạt nước ấm 4–6 tiếng cho nứt nanh.',
          'Trải khăn giấy ẩm xuống khay, rắc hạt đều, không chồng lên nhau.',
          'Xịt ẩm 2 lần/ngày, để chỗ thoáng mát, tránh nắng gắt.',
          'Sau 5–7 ngày mầm cao 5–8cm là cắt ăn được.',
        ],
        tip: 'Giữ ẩm đều nhưng đừng để đọng nước — úng là hỏng cả khay.',
        img: `${W}thumb/a/a6/Rau_mam.JPG/500px-Rau_mam.JPG`,
        imgAlt: 'Khay rau mầm',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Microgreen' },
      },
      {
        id: 'hanh-la',
        title: 'Tái sinh hành lá từ gốc',
        emoji: '🧅',
        time: '7–10 ngày',
        level: 'Dễ',
        intro: 'Tận dụng gốc hành bỏ đi, mọc lại nhiều lần.',
        need: ['Gốc hành lá (chừa ~5cm)', 'Cốc nước hoặc chậu đất'],
        steps: [
          'Giữ lại phần gốc trắng còn rễ, dài khoảng 5cm.',
          'Cắm vào cốc nước sao cho ngập rễ, để chỗ có nắng nhẹ.',
          'Thay nước mỗi 1–2 ngày cho khỏi hôi.',
          'Vài ngày là lá xanh mọc lên; cắt phần lá, chừa gốc để mọc tiếp.',
        ],
        tip: 'Trồng xuống đất sau 1 tuần sẽ khoẻ và mọc bền hơn cắm nước mãi.',
        img: `${W}thumb/d/da/CSA-Red-Spring-Onions.jpg/500px-CSA-Red-Spring-Onions.jpg`,
        imgAlt: 'Hành lá',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Scallion' },
      },
      {
        id: 'gia-do',
        title: 'Làm giá đỗ tại nhà',
        emoji: '🫘',
        time: '3–4 ngày',
        level: 'Vừa',
        intro: 'Giòn ngọt, sạch, không hoá chất.',
        need: ['Đậu xanh', 'Rổ/hộp có lỗ thoát nước', 'Khăn tối màu'],
        steps: [
          'Ngâm đậu xanh nước ấm 6–8 tiếng, bỏ hạt nổi/lép.',
          'Cho vào rổ, phủ khăn ẩm, đặt nơi TỐI (giá ưa tối mới mập trắng).',
          'Tưới nước 2–3 lần/ngày rồi để ráo hoàn toàn.',
          'Sau 3–4 ngày giá dài là thu hoạch.',
        ],
        tip: 'Càng tối và càng ráo nước, giá càng trắng mập, không bị thối.',
        img: `${W}thumb/9/97/Organic_mixed_beans_shoots.jpg/500px-Organic_mixed_beans_shoots.jpg`,
        imgAlt: 'Giá đỗ',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Bean_sprout' },
      },
      {
        id: 'gieo-cai',
        title: 'Gieo rau cải trong thùng xốp',
        emoji: '🥗',
        time: '25–30 ngày',
        level: 'Vừa',
        intro: 'Một thùng xốp ban công là đủ rau ăn dần.',
        need: ['Thùng xốp (đục lỗ đáy)', 'Đất sạch/đất trồng', 'Hạt cải', 'Bình tưới'],
        steps: [
          'Đục vài lỗ đáy thùng cho thoát nước, đổ đất dày ~10cm.',
          'Gieo hạt thưa, phủ lớp đất mỏng, tưới ẩm.',
          'Đặt nơi có nắng 4–6 tiếng/ngày, tưới sáng sớm hoặc chiều mát.',
          'Khi cây mọc dày thì tỉa bớt cho cây còn lại lớn nhanh.',
        ],
        tip: 'Tưới lúc sáng sớm/chiều mát; tránh tưới giữa trưa nắng gắt làm cây sốc nhiệt.',
        img: `${W}thumb/8/8b/A_vegetable_farm.jpg/500px-A_vegetable_farm.jpg`,
        imgAlt: 'Luống rau xanh',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Leaf_vegetable' },
      },
      {
        id: 'tuoi-dung',
        title: 'Tưới nước đúng cách',
        emoji: '💧',
        time: 'Mỗi ngày',
        level: 'Dễ',
        intro: 'Cây chết vì tưới sai nhiều hơn vì thiếu nước.',
        need: ['Bình tưới vòi sen', 'Quan sát đất'],
        steps: [
          'Thọc ngón tay vào đất ~2cm; khô thì tưới, còn ẩm thì khoan.',
          'Tưới vào gốc, tránh xối mạnh lên lá non.',
          'Tưới sáng sớm hoặc chiều mát, không tưới giữa trưa.',
          'Chậu phải thoát nước tốt — đọng nước lâu sẽ úng rễ.',
        ],
        tip: 'Nguyên tắc vàng: đất khô mới tưới, tưới thì tưới đẫm rồi để ráo.',
        img: `${W}thumb/1/1b/MetalwateringcansDec08.jpg/500px-MetalwateringcansDec08.jpg`,
        imgAlt: 'Bình tưới cây',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Watering_can' },
      },
      {
        id: 'u-phan',
        title: 'Ủ rác bếp thành phân',
        emoji: '♻️',
        time: '3–4 tuần',
        level: 'Vừa',
        intro: 'Biến vỏ rau củ thành phân bón, giảm rác thải.',
        need: ['Vỏ rau củ, bã cà phê', 'Thùng có nắp', 'Ít đất/lá khô'],
        steps: [
          'Cắt nhỏ vỏ rau củ (đừng cho thịt cá, dầu mỡ — gây hôi, chuột).',
          'Xếp xen kẽ một lớp rác bếp, một lớp đất/lá khô.',
          'Đảo trộn mỗi tuần cho thoáng khí, giữ ẩm vừa phải.',
          'Sau 3–4 tuần hỗn hợp tơi, nâu, mùi đất là dùng bón cây được.',
        ],
        tip: 'Chỉ ủ đồ thực vật; tránh thịt, cá, dầu mỡ để không hôi và hút chuột bọ.',
        img: `${W}thumb/e/e5/Compost_site_germany.JPG/500px-Compost_site_germany.JPG`,
        imgAlt: 'Đống ủ phân hữu cơ',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Compost' },
      },
    ],
  },
  {
    key: 'chup',
    label: 'Chụp ảnh',
    emoji: '📷',
    blurb: 'Chỉ với điện thoại, vài nguyên tắc nhỏ là ảnh đã đẹp hơn hẳn — không cần máy xịn.',
    skills: [
      {
        id: 'cam-may',
        title: 'Cầm máy vững & lau ống kính',
        emoji: '🤳',
        time: 'Đọc 2 phút',
        level: 'Dễ',
        intro: 'Hai việc nhỏ này làm ảnh nét hơn ngay lập tức.',
        need: ['Điện thoại/máy ảnh', 'Khăn mềm lau kính'],
        steps: [
          'Lau ống kính trước khi chụp — dấu vân tay làm ảnh mờ đục.',
          'Cầm bằng hai tay, khuỷu tay tì sát người cho chắc.',
          'Bấm nhẹ nút chụp (hoặc dùng nút âm lượng) để đỡ rung.',
          'Tì máy vào tường/bàn khi thiếu sáng để khỏi nhoè.',
        ],
        tip: 'Chỉ cần lau kính + cầm chắc hai tay, ảnh đã nét hơn nửa rồi.',
        img: `${W}thumb/2/2b/Photographer_Photographing_Nevada_Mountains.jpg/500px-Photographer_Photographing_Nevada_Mountains.jpg`,
        imgAlt: 'Người đang cầm máy chụp ảnh',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Photography' },
      },
      {
        id: 'bo-cuc',
        title: 'Bố cục một phần ba (1/3)',
        emoji: '🔲',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Quy tắc kinh điển giúp ảnh cân đối, có hồn.',
        need: ['Điện thoại có bật lưới (gridlines)'],
        steps: [
          'Vào cài đặt camera, bật "Lưới" → màn hình chia 9 ô.',
          'Đặt chủ thể (người, vật) vào một trong 4 giao điểm, đừng đặt chính giữa.',
          'Khi chụp phong cảnh, để đường chân trời trùng đường ngang 1/3 (trên hoặc dưới).',
          'Chừa khoảng trống phía trước hướng nhìn/di chuyển của chủ thể.',
        ],
        tip: 'Đặt chủ thể lệch về giao điểm trông tự nhiên hơn nhiều so với đặt giữa.',
        img: `${W}c/ce/Rivertree_thirds_md.gif`,
        imgAlt: 'Minh hoạ quy tắc một phần ba',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Rule_of_thirds' },
      },
      {
        id: 'anh-sang',
        title: 'Tận dụng ánh sáng & giờ vàng',
        emoji: '🌅',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Ánh sáng đẹp quan trọng hơn máy đắt tiền.',
        need: ['Quan sát hướng nắng'],
        steps: [
          'Để nguồn sáng (mặt trời, cửa sổ) ở phía sau lưng người chụp, chiếu vào chủ thể.',
          'Chụp lúc "giờ vàng" — sáng sớm hoặc gần hoàng hôn, nắng ấm và dịu.',
          'Tránh nắng gắt giữa trưa: bóng đổ cứng, mặt người tối/loá.',
          'Trong nhà: cho chủ thể quay mặt ra phía cửa sổ.',
        ],
        tip: 'Ngược nắng làm tối mặt; xoay lại để nắng chiếu vào chủ thể là ăn ngay.',
        img: `${W}thumb/d/d2/Newbury_Racecourse_Road.jpg/500px-Newbury_Racecourse_Road.jpg`,
        imgAlt: 'Cảnh chụp trong giờ vàng',
        source: {
          label: 'Wikipedia',
          url: 'https://en.wikipedia.org/wiki/Golden_hour_(photography)',
        },
      },
      {
        id: 'chan-dung',
        title: 'Chụp chân dung xoá phông',
        emoji: '🧑‍🎤',
        time: 'Đọc 3 phút',
        level: 'Vừa',
        intro: 'Cho người nổi bật, hậu cảnh mờ mịn.',
        need: ['Điện thoại có chế độ Chân dung/Portrait'],
        steps: [
          'Cho người đứng cách xa hậu cảnh vài mét (càng xa càng dễ xoá phông).',
          'Bật chế độ "Chân dung", lấy nét vào mắt.',
          'Đưa máy ngang tầm mắt người chụp, đừng chụp từ dưới lên.',
          'Chọn hậu cảnh gọn gàng, ít chi tiết rối.',
        ],
        tip: 'Lấy nét vào mắt và chụp ngang tầm mắt là bí quyết của ảnh chân dung đẹp.',
        img: `${W}thumb/e/e4/Self_portrait_of_Edward_Sheriff_Curtis.jpg/500px-Self_portrait_of_Edward_Sheriff_Curtis.jpg`,
        imgAlt: 'Ảnh chân dung',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Portrait_photography' },
      },
      {
        id: 'lay-net',
        title: 'Lấy nét & chỉnh sáng',
        emoji: '🔆',
        time: 'Đọc 3 phút',
        level: 'Vừa',
        intro: 'Làm chủ độ nét và độ sáng chỉ bằng ngón tay.',
        need: ['Điện thoại bất kỳ'],
        steps: [
          'Chạm vào chủ thể trên màn hình để máy lấy nét đúng chỗ.',
          'Sau khi chạm, kéo biểu tượng mặt trời (☀) lên/xuống để chỉnh sáng.',
          'Giữ tay lâu trên màn hình để KHOÁ nét/sáng (AE/AF lock) khi bố cục lại.',
          'Nếu ảnh ngược sáng làm tối mặt, tăng sáng lên một chút.',
        ],
        tip: 'Chạm vào vùng muốn rõ rồi chỉnh sáng — đừng để máy tự quyết hết.',
        img: `${W}thumb/9/99/Canon_PowerShot_A95_-_front_and_back.jpg/500px-Canon_PowerShot_A95_-_front_and_back.jpg`,
        imgAlt: 'Máy ảnh kỹ thuật số',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Exposure_(photography)' },
      },
      {
        id: 'dien-thoai',
        title: 'Mẹo chụp đẹp bằng điện thoại',
        emoji: '📱',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Vắt kiệt khả năng của camera điện thoại.',
        need: ['Điện thoại'],
        steps: [
          'Bật lưới + HDR trong cài đặt camera.',
          'Lại gần chủ thể thay vì zoom số (zoom số làm ảnh vỡ hạt).',
          'Dọn hậu cảnh lộn xộn trước khi bấm máy.',
          'Chỉnh nhẹ sáng/tương phản khi sửa ảnh — đừng lạm dụng filter cho tự nhiên.',
        ],
        tip: 'Bước chân lại gần luôn đẹp hơn zoom số; filter nhẹ tay thôi.',
        img: `${W}thumb/e/e7/Handyaufnahme_des_Sonnenuntergangs_als_Zeitraffer_20200909_DSC3277.jpg/500px-Handyaufnahme_des_Sonnenuntergangs_als_Zeitraffer_20200909_DSC3277.jpg`,
        imgAlt: 'Chụp hoàng hôn bằng điện thoại',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Camera_phone' },
      },
    ],
  },
  {
    key: 'da',
    label: 'Chăm sóc da',
    emoji: '🧴',
    blurb:
      'Da tuổi học sinh còn mỏng và dễ nổi mụn — chăm đơn giản, đều đặn, dịu nhẹ là tốt nhất.',
    skills: [
      {
        id: 'rua-mat',
        title: 'Rửa mặt đúng cách',
        emoji: '💧',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Bước nền tảng — sạch nhẹ nhàng, không quá tay.',
        need: ['Sữa rửa mặt dịu nhẹ', 'Nước ấm', 'Khăn sạch'],
        steps: [
          'Rửa tay sạch trước, làm ướt mặt bằng nước ấm (không nóng).',
          'Lấy một lượng nhỏ sữa rửa mặt, massage tròn nhẹ 30–60 giây.',
          'Rửa lại thật sạch, thấm khô bằng khăn sạch (đừng chà mạnh).',
          'Rửa 2 lần/ngày — sáng và tối; không rửa quá nhiều lần.',
        ],
        tip: 'Rửa quá nhiều/nước quá nóng làm da khô rồi tiết dầu nhiều hơn.',
        img: `${W}thumb/1/1e/Skin_care_cosmetics.jpg/500px-Skin_care_cosmetics.jpg`,
        imgAlt: 'Sản phẩm chăm sóc da',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Skin_care' },
      },
      {
        id: 'duong-am',
        title: 'Dưỡng ẩm cho da',
        emoji: '🧴',
        time: 'Đọc 2 phút',
        level: 'Dễ',
        intro: 'Da đủ ẩm sẽ khoẻ, ít bong tróc và bớt tiết dầu.',
        need: ['Kem dưỡng ẩm dịu nhẹ'],
        steps: [
          'Thoa kem ngay sau khi rửa mặt, lúc da còn hơi ẩm.',
          'Lấy lượng vừa đủ, tán đều khắp mặt và cổ.',
          'Chọn loại "không gây bít tắc" (non-comedogenic) nếu da dễ mụn.',
          'Da dầu vẫn cần dưỡng ẩm — chọn loại mỏng nhẹ (gel).',
        ],
        tip: 'Da dầu mà bỏ dưỡng ẩm sẽ càng tiết dầu để tự bù — đừng bỏ bước này.',
        img: `${W}thumb/3/33/White_Petrolatum1.jpg/500px-White_Petrolatum1.jpg`,
        imgAlt: 'Hũ kem dưỡng ẩm',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Moisturizer' },
      },
      {
        id: 'chong-nang',
        title: 'Kem chống nắng (quan trọng nhất)',
        emoji: '☀️',
        time: 'Đọc 3 phút',
        level: 'Dễ',
        intro: 'Bước chống lão hoá và thâm mụn hiệu quả nhất.',
        need: ['Kem chống nắng SPF 30+ dịu nhẹ'],
        steps: [
          'Thoa mỗi sáng, kể cả trời mây hay ngồi gần cửa sổ.',
          'Dùng đủ lượng — khoảng 2 đốt ngón tay cho cả mặt.',
          'Đây là bước CUỐI của buổi sáng (sau dưỡng ẩm).',
          'Nếu ra nắng nhiều, thoa lại sau mỗi 2–3 tiếng.',
        ],
        tip: 'Chống nắng đều mỗi ngày giúp ngừa thâm, nám và lão hoá hơn mọi loại kem đắt tiền.',
        img: `${W}thumb/6/60/Sunscreen_on_back_under_normal_and_UV_light.jpg/500px-Sunscreen_on_back_under_normal_and_UV_light.jpg`,
        imgAlt: 'Kem chống nắng nhìn dưới tia UV',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Sunscreen' },
      },
      {
        id: 'da-mun',
        title: 'Da mụn: chăm đúng, đừng nặn',
        emoji: '🚫',
        time: 'Đọc 3 phút',
        level: 'Vừa',
        intro: 'Mụn tuổi dậy thì là bình thường — xử lý sai mới để lại sẹo.',
        need: ['Kiên nhẫn', 'Gối/khăn sạch'],
        steps: [
          'Tuyệt đối không tự nặn, cạy mụn — dễ thâm, sẹo và nhiễm trùng.',
          'Hạn chế sờ tay lên mặt; lau sạch màn hình điện thoại hay áp vào má.',
          'Thay vỏ gối, khăn mặt thường xuyên cho sạch.',
          'Mụn nhiều/sưng nặng → đi khám bác sĩ da liễu, đừng tự ý bôi thuốc mạnh.',
        ],
        tip: 'Một nốt mụn để tự lành vài ngày; nhưng nặn sai có thể để lại vết thâm hàng tháng.',
        img: `${W}thumb/f/f0/Acne_vulgaris_on_a_very_oily_skin.jpg/500px-Acne_vulgaris_on_a_very_oily_skin.jpg`,
        imgAlt: 'Da bị mụn',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Acne' },
      },
      {
        id: 'cham-tu-trong',
        title: 'Chăm da từ bên trong',
        emoji: '🥤',
        time: 'Đọc 2 phút',
        level: 'Dễ',
        intro: 'Làn da đẹp bắt đầu từ lối sống, không chỉ mỹ phẩm.',
        need: ['Thói quen tốt mỗi ngày'],
        steps: [
          'Uống đủ nước trong ngày.',
          'Ngủ đủ 7–9 tiếng — thiếu ngủ làm da xỉn và dễ mụn.',
          'Ăn nhiều rau quả, hạn chế đồ ngọt và đồ chiên rán.',
          'Vận động, giảm căng thẳng (stress cũng gây mụn).',
        ],
        tip: 'Ngủ đủ và uống đủ nước nhiều khi hiệu quả hơn cả một tủ mỹ phẩm.',
        img: `${W}thumb/a/ad/Clean_water_for_a_village_in_West_Lombok_%2810686572086%29.jpg/500px-Clean_water_for_a_village_in_West_Lombok_%2810686572086%29.jpg`,
        imgAlt: 'Ly nước sạch',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Drinking_water' },
      },
      {
        id: 'thoi-quen',
        title: 'Thói quen nên tránh',
        emoji: '⚠️',
        time: 'Đọc 3 phút',
        level: 'Vừa',
        intro: 'Tránh sai lầm phổ biến còn quan trọng hơn mua thêm sản phẩm.',
        need: ['Sự tỉnh táo khi mua mỹ phẩm'],
        steps: [
          'Đừng đổi sản phẩm liên tục — da cần 3–4 tuần để quen.',
          'Đừng dùng quá nhiều sản phẩm/treatment mạnh cùng lúc.',
          'Thử sản phẩm mới ở một vùng da nhỏ trước (patch test) 1–2 ngày.',
          'Tẩy tế bào chết vừa phải (1–2 lần/tuần), đừng lạm dụng.',
        ],
        tip: 'Cảnh giác với quảng cáo "trắng cấp tốc" — đơn giản, đều đặn mới bền và an toàn.',
        img: `${W}thumb/b/bc/Cosmetics.JPG/500px-Cosmetics.JPG`,
        imgAlt: 'Nhiều loại mỹ phẩm',
        source: { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Cosmetics' },
      },
    ],
  },
]
